<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_script_include">
    <sys_script_include action="INSERT_OR_UPDATE">
        <access>package_private</access>
        <active>true</active>
        <api_name>x_arcag_mail.PingenAPI</api_name>
        <caller_access/>
        <client_callable>false</client_callable>
        <description>Abstract helper class for Pingen API access</description>
        <name>PingenAPI</name>
        <script><![CDATA[/* global gs, x_arcag_sic */
/* eslint no-undef: "error" */
class PingenAPI {
	constructor(pingenHost = "api-staging.pingen.com", organisation = "<invalid>") {
		this.configuration = {
			pingen_host: pingenHost,
			organisation: organisation,
		};
	}

	/**
	 * Handle an exception that arose during the exection of a RESTMessageV2
	 * (2024-10-30 / BPF)
	 *
	 * Callers: All methods implemented in child classes!
	 *
	 * @protected
	 * @param {String} endpoint - The name of the message (e.g. "file-upload", not the endpoint URL)
	 * @param {Error} exception - The catched exception
	 * @param {Object} result - The current result object
	 *
	 * @return {Object} - An object containing the execution information of the method,
	 *                    {Error} error - The exception
	 *                    {String} message - An system internal message about the state of the execution
	 * 					  everything will be assigned to the result parameter
	 */
	_handleException(endpoint, exception, result) {
		if (x_arcag_sic?.AutomatedIncident?.enabled()) {
			const message = [`The endpoint "${endpoint}" failed with the message: "${exception.message}"\n Please investigate the reason for this (invalid token, pingen outtage (see https://status.pingen.com/)).`];
			message.push(`Error Message: ${exception.message}`);
			message.push(`Error Trace: ${exception.stack}`);
			message.push(`Configuration: ${JSON.stringify(this.configuration, null, 2)}`);
			x_arcag_sic.AutomatedIncident.create(`[PingenAPI] ${endpoint} failed`, message.join("\n"));
		}
		const errorResult = {
			message: gs.getMessage("postal_mail_pingen_error"),
			error: exception,
		};

		return Object.assign(result, errorResult);
	}
}]]></script>
        <sys_class_name>sys_script_include</sys_class_name>
        <sys_created_by>bjoern.pfoster</sys_created_by>
        <sys_created_on>2024-10-30 13:17:10</sys_created_on>
        <sys_id>f50baab593e99250f0e734ba6aba1092</sys_id>
        <sys_mod_count>9</sys_mod_count>
        <sys_name>PingenAPI</sys_name>
        <sys_package display_value="Postal PDF" source="x_arcag_mail">22fbe5fd93659250f0e734ba6aba1095</sys_package>
        <sys_policy>read</sys_policy>
        <sys_scope display_value="Postal PDF">22fbe5fd93659250f0e734ba6aba1095</sys_scope>
        <sys_update_name>sys_script_include_f50baab593e99250f0e734ba6aba1092</sys_update_name>
        <sys_updated_by>bjoern.pfoster</sys_updated_by>
        <sys_updated_on>2024-10-31 10:42:58</sys_updated_on>
    </sys_script_include>
</record_update>
